import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Share,
} from 'react-native';
import { COLORS, FONTS, SPACING, BORDER_RADIUS, SHADOW } from '../constants/theme';

const RESULT_CONFIG = {
  'Good Fit': {
    color: COLORS.goodFit,
    bg: '#E8F5EE',
    icon: '✅',
    headline: 'Strong Candidate',
    description:
      'This candidate is a strong match for the position. Skills, experience, and qualifications align well with the job requirements.',
    recommendation: 'Recommended for interview',
    recommendationColor: COLORS.goodFit,
  },
  'Potential Fit': {
    color: COLORS.potentialFit,
    bg: '#FEF3C7',
    icon: '⚠️',
    headline: 'Possible Candidate',
    description:
      'This candidate has some relevant qualifications but may not fully meet all requirements. Consider a preliminary screening call.',
    recommendation: 'Consider for screening',
    recommendationColor: COLORS.potentialFit,
  },
  'No Fit': {
    color: COLORS.noFit,
    bg: '#FEE2E2',
    icon: '❌',
    headline: 'Not Recommended',
    description:
      'This candidate's profile does not sufficiently match the job requirements based on the provided texts.',
    recommendation: 'Not recommended at this time',
    recommendationColor: COLORS.noFit,
  },
};

// Fallback for unexpected labels
const getConfig = (label) =>
  RESULT_CONFIG[label] || {
    color: COLORS.textSecondary,
    bg: COLORS.background,
    icon: '❓',
    headline: label,
    description: 'Analysis complete.',
    recommendation: 'Review manually',
    recommendationColor: COLORS.textSecondary,
  };

function ScoreBar({ label, value, color }) {
  const pct = Math.round(value * 100);
  return (
    <View style={scoreStyles.row}>
      <Text style={scoreStyles.label}>{label}</Text>
      <View style={scoreStyles.barBg}>
        <View style={[scoreStyles.barFill, { width: `${pct}%`, backgroundColor: color }]} />
      </View>
      <Text style={scoreStyles.pct}>{pct}%</Text>
    </View>
  );
}

const scoreStyles = StyleSheet.create({
  row: { marginBottom: SPACING.sm },
  label: { fontSize: FONTS.sizes.sm, color: COLORS.textSecondary, marginBottom: 4 },
  barBg: {
    height: 10,
    backgroundColor: COLORS.border,
    borderRadius: BORDER_RADIUS.full,
    overflow: 'hidden',
  },
  barFill: { height: '100%', borderRadius: BORDER_RADIUS.full },
  pct: {
    fontSize: FONTS.sizes.xs,
    color: COLORS.textMuted,
    textAlign: 'right',
    marginTop: 2,
  },
});

export default function ResultScreen({ route, navigation }) {
  const { result, resumeText, jobDescText } = route.params;

  const config = getConfig(result.label);
  const confidence = Math.round((result.confidence || 0) * 100);
  const scores = result.scores || {};

  const handleShare = async () => {
    try {
      await Share.share({
        message:
          `PIDE Resume Analysis Result\n\n` +
          `Result: ${result.label}\n` +
          `Confidence: ${confidence}%\n\n` +
          `Recommendation: ${config.recommendation}\n\n` +
          `Generated by PIDE Resume Analyzer`,
      });
    } catch (error) {
      // ignore share cancellation
    }
  };

  return (
    <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
      {/* Result Header */}
      <View style={[styles.resultHeader, { backgroundColor: config.color }]}>
        <Text style={styles.resultIcon}>{config.icon}</Text>
        <Text style={styles.resultLabel}>{result.label}</Text>
        <Text style={styles.resultHeadline}>{config.headline}</Text>
        <View style={styles.confidenceBadge}>
          <Text style={styles.confidenceText}>{confidence}% confidence</Text>
        </View>
      </View>

      <View style={styles.body}>
        {/* Description Card */}
        <View style={[styles.descCard, { backgroundColor: config.bg, borderColor: config.color }]}>
          <Text style={[styles.descText, { color: config.color }]}>{config.description}</Text>
        </View>

        {/* Recommendation */}
        <View style={styles.recRow}>
          <Text style={styles.recLabel}>Recommendation:</Text>
          <View style={[styles.recBadge, { backgroundColor: config.bg, borderColor: config.color }]}>
            <Text style={[styles.recText, { color: config.color }]}>
              {config.recommendation}
            </Text>
          </View>
        </View>

        {/* Confidence Scores */}
        {Object.keys(scores).length > 0 && (
          <View style={styles.card}>
            <Text style={styles.cardTitle}>Probability Breakdown</Text>
            <ScoreBar
              label="Good Fit"
              value={scores['Good Fit'] || 0}
              color={COLORS.goodFit}
            />
            <ScoreBar
              label="Potential Fit"
              value={scores['Potential Fit'] || 0}
              color={COLORS.potentialFit}
            />
            <ScoreBar
              label="No Fit"
              value={scores['No Fit'] || 0}
              color={COLORS.noFit}
            />
          </View>
        )}

        {/* Input Preview */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Analysis Summary</Text>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryKey}>Resume length:</Text>
            <Text style={styles.summaryVal}>
              {resumeText.trim().split(/\s+/).length} words
            </Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryKey}>Job desc. length:</Text>
            <Text style={styles.summaryVal}>
              {jobDescText.trim().split(/\s+/).length} words
            </Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryKey}>Model:</Text>
            <Text style={styles.summaryVal}>Random Forest Classifier</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryKey}>Model accuracy:</Text>
            <Text style={styles.summaryVal}>85% on test set</Text>
          </View>
        </View>

        {/* Actions */}
        <TouchableOpacity style={styles.shareButton} onPress={handleShare} activeOpacity={0.85}>
          <Text style={styles.shareButtonText}>📤 Share Result</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.newButton}
          onPress={() => navigation.navigate('Analyzer')}
          activeOpacity={0.85}
        >
          <Text style={styles.newButtonText}>Analyze Another Resume</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.homeButton}
          onPress={() => navigation.navigate('Home')}
          activeOpacity={0.7}
        >
          <Text style={styles.homeButtonText}>Back to Home</Text>
        </TouchableOpacity>

        {/* Disclaimer */}
        <Text style={styles.disclaimer}>
          ⚠️ This tool is an AI-assisted screening aid. Final hiring decisions should involve human
          judgment and review of the full application.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  resultHeader: {
    paddingTop: SPACING.xxl,
    paddingBottom: SPACING.xl,
    paddingHorizontal: SPACING.lg,
    alignItems: 'center',
  },
  resultIcon: {
    fontSize: 56,
    marginBottom: SPACING.sm,
  },
  resultLabel: {
    fontSize: FONTS.sizes.xxl,
    fontWeight: '800',
    color: COLORS.secondary,
    letterSpacing: 0.5,
  },
  resultHeadline: {
    fontSize: FONTS.sizes.md,
    color: 'rgba(255,255,255,0.9)',
    marginTop: 4,
  },
  confidenceBadge: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingVertical: SPACING.xs,
    paddingHorizontal: SPACING.md,
    borderRadius: BORDER_RADIUS.full,
    marginTop: SPACING.md,
  },
  confidenceText: {
    color: COLORS.secondary,
    fontWeight: '700',
    fontSize: FONTS.sizes.sm,
  },
  body: {
    padding: SPACING.lg,
  },
  descCard: {
    borderWidth: 1.5,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.md,
  },
  descText: {
    fontSize: FONTS.sizes.sm,
    lineHeight: 22,
    fontWeight: '500',
  },
  recRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.lg,
    flexWrap: 'wrap',
    gap: SPACING.sm,
  },
  recLabel: {
    fontSize: FONTS.sizes.sm,
    color: COLORS.textSecondary,
    fontWeight: '600',
  },
  recBadge: {
    borderWidth: 1,
    borderRadius: BORDER_RADIUS.full,
    paddingVertical: 4,
    paddingHorizontal: SPACING.sm,
  },
  recText: {
    fontSize: FONTS.sizes.sm,
    fontWeight: '700',
  },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: BORDER_RADIUS.md,
    padding: SPACING.md,
    marginBottom: SPACING.md,
    ...SHADOW.small,
  },
  cardTitle: {
    fontSize: FONTS.sizes.md,
    fontWeight: '700',
    color: COLORS.textPrimary,
    marginBottom: SPACING.md,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: SPACING.xs,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  summaryKey: {
    fontSize: FONTS.sizes.sm,
    color: COLORS.textSecondary,
  },
  summaryVal: {
    fontSize: FONTS.sizes.sm,
    color: COLORS.textPrimary,
    fontWeight: '500',
  },
  shareButton: {
    backgroundColor: COLORS.primaryDark,
    paddingVertical: SPACING.md,
    borderRadius: BORDER_RADIUS.md,
    alignItems: 'center',
    marginBottom: SPACING.sm,
    ...SHADOW.medium,
  },
  shareButtonText: {
    color: COLORS.secondary,
    fontWeight: '700',
    fontSize: FONTS.sizes.md,
  },
  newButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: SPACING.md,
    borderRadius: BORDER_RADIUS.md,
    alignItems: 'center',
    marginBottom: SPACING.sm,
    ...SHADOW.small,
  },
  newButtonText: {
    color: COLORS.secondary,
    fontWeight: '700',
    fontSize: FONTS.sizes.md,
  },
  homeButton: {
    paddingVertical: SPACING.md,
    borderRadius: BORDER_RADIUS.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: SPACING.lg,
  },
  homeButtonText: {
    color: COLORS.textSecondary,
    fontWeight: '500',
    fontSize: FONTS.sizes.sm,
  },
  disclaimer: {
    fontSize: FONTS.sizes.xs,
    color: COLORS.textMuted,
    lineHeight: 18,
    textAlign: 'center',
    paddingHorizontal: SPACING.md,
    paddingBottom: SPACING.lg,
  },
});
